# Generated by Django 5.0.1 on 2024-01-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_comment"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="name",),
        migrations.RemoveField(model_name="comment", name="username",),
        migrations.DeleteModel(name="bid",),
        migrations.DeleteModel(name="listing",),
        migrations.DeleteModel(name="comment",),
    ]
