# Generated by Django 5.0.1 on 2024-01-25 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_remove_comment_name_remove_comment_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="listing",
            fields=[
                ("listing_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=64)),
                ("price", models.FloatField()),
                (
                    "listee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_hist",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
        ),
    ]
