# Generated by Django 5.0.1 on 2024-01-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_listing"),
    ]

    operations = [
        migrations.DeleteModel(name="listing",),
    ]
